export const emoji_list = [
    {name: "eco+", path: "ecoplus1.png"},
    {name: "lmfao", path: "ecoplus2.png"},
    {name: "thinkill", path: "ecoplus3.png"},
    {name: "chico", path: "ecoplus4.png"},
    {name: "men", path: "men.png"},
    {name: "wamen1", path: "wamen.png"},
    {name: "wamen2", path: "woamen.png"},
    {name: "pepegun", path: "pepe1.png"},
    {name: "pepeinspect", path: "pepe2.png"},
    {name: "pepehappy", path: "pepe3.png"},
    {name: "clown", path: "pepe4.png"},
    {name: "pepesueur", path: "pepe5.png"},
    {name: "pepesueur2", path: "pepe6.png"},
    {name: "risisueur", path: "risitas1.png"},
    {name: "risitas", path: "risitas2.png"},
]